language: node_js
node_js:
  - "12"

# Remove shallow cloning for Sonar analysis
git:
  depth: false

branches:
  only:
  - master

before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

after_success:
  - fossa init
  - fossa analyze
  - npm run coverage:send
  - sonar-scanner

addons:
  sonarcloud:
    organization: "daniel-duarte"
    token:
      secure: $SONAR_TOKEN
